version: '3.7'

services:

  cron:
    image: corycollier/wordpress:cron
    env_file: .env
    command: ["cron", "-f"]
    depends_on:
      - web
    volumes:
      - wp:/var/www/html
      - tmp:/tmp

  db:
    image  : mariadb:10.7
    env_file: .env
    restart: unless-stopped
    depends_on:
      - loki
    volumes:
      - db:/var/lib/mysql
      - tmp:/tmp

  web:
    image : corycollier/wordpress:web
    env_file: .env
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - wp:/var/www/html
    depends_on:
      - db

volumes:
  db:
  tmp:
  wp:
